services:
  - type: web
    name: kurukshetra
    env: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
    disk:
      name: sqlite-data
      mountPath: /opt/data
      sizeGB: 1
  - type: web
    name: kurukshetra-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://kurukshetra-ruby.vercel.app
    healthCheckPath: /health
    autoDeploy: true
