services:
  - type: web
    name: kurukshetra-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://kurukshetra-ruby.vercel.app
      - key: UPLOAD_DIR
        value: uploads
      - key: JWT_SECRET
        fromGroup: kurukshetra-secrets
      - key: MONGODB_URI
        fromGroup: kurukshetra-secrets