services:
  - type: web
    name: kurukshetra
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_PATH
        value: ./data/database.sqlite
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 10
      - key: DB_TYPE
        value: sqlite
      - key: SEED_DATA
        value: true
      - key: MONGO_URI
        sync: false