services:
  - type: web
    name: kurukshetra-server
    env: node
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /opt/render/data/kurukshetra.sqlite
    disk:
      name: sqlite-data
      mountPath: /opt/render/data
      sizeGB: 1